baseURL = "https://cranky-lalande-9d501c.netlify.com/"
languageCode = "en-us"
title = "Metricly Docs"
theme = "docdock"
[params]
#themeStyle = "flex"
themeStyle = "original"
#themeVariant = "gray"
disableHomeIcon = true
[outputs]
home = [ "HTML", "RSS", "JSON"]
