baseURL = "https://docs.metricly.com/"
languageCode = "en-us"
title = "CloudWisdom Docs"
theme = "docdock"

[params]
#themeStyle = "flex"
themeStyle = "original"
#themeVariant = "grey"
disableHomeIcon = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = " <i class='fa fa-compass fa-lg'></i> Virtana"
identifier = "virtana"
url = "https://www.virtana.com/"
weight = 1
