baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Metricly Docs"
theme = "docdock"
[params]
themeStyle = "flex"
themeVariant= "gray"
disableHomeIcon = true
[outputs]
home = [ "HTML", "RSS", "JSON"]
